### PR TITLE
Build: Bump dependencies

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
I lost access to this repo. @pjackson28 can you add this repo to the release management?

**Comment by nschonni** [comment]
@LaurentGoderre I swapped the tagged version of `node-git-simple` with the version you published

**Comment by nschonni** [comment]
@LaurentGoderre we'll need to publish a new version to NPM so the other repos can start using the NPM sub-dependency

**Comment by LaurentGoderre** [comment]
Yeah....I tried to avoid pollutting their index with our custom stuff but I guess everyone does it.

**Comment by LaurentGoderre** [comment]
I wish there was a ciDependencies config for npm where we could specify the stuff that is only needed for the CI

**Comment by nschonni** [comment]
There kind of is, but it doesn't work for Grunt. You just use scripts and the acutal CI config files to install other command line tools.

**Comment by LaurentGoderre** [comment]
Anyways, I published to npm

**Comment by nschonni** [comment]
k, I guess you can check out how the Travis Caching will handle it by restarting a build on wet-boew\master now.

**Comment by LaurentGoderre** [comment]
How will we know if it worked?

**Comment by nschonni** [comment]
You'll see what was installed in the Travis log

**Pull request merged**
